### ISSUE TITLE
Propose to have talks page have a table of talk titles 

### ISSUE THREAD

**Issue by elfgoh** [gopherconsg/website#36]
https://github.com/gopherconsg/website/tree/talks-page

so that it is easy to review the schedule

cc @hongkheng

**Comment by elfgoh** [comment]
Suggest to be completed until schedule is finalised

**Comment by hongkheng** [comment]
Having a table meaning to have some line to separate them?

**Comment by elfgoh** [comment]
Not really. Context of this issue: right now it seems very difficult to view the last talk title without scrolling all the way down. I am proposing to have a table at the top with just talk titles only.

**Comment by hongkheng** [comment]
let me update the excel file
