### ISSUE TITLE
More detailed directions to conference and workshop venues

### ISSUE THREAD

**Issue by hongkheng** [gopherconsg/website#79]
It will be helpful to our conference speakers and attendees and maybe organiser(s)? to know the directions to the venues.

Information needed:
- **Actual location of the conference and workshop**. Should include, the actual level and building number or unit number of the Google office. For Amara hotel, make sure there is enough signages to direct the attendees.
- Directions to nearest bus stops
- Directions to nearest MRT stations
- Directions by Uber/Grab/Taxis
- Relevant pictures or photos of the actual venues or locations or key landmarks

**Comment by cheeaun** [comment]
Few more infos:

- Directions to MRT stations should include exits/entrances too (Exit A etc). My https://railrouter.sg/ can help with that. Citymapper and Google Maps include those too but only when finding for directions.
- Directions by Uber/Grab, we can include the promo codes as well. https://www.facebook.com/TaxiBotsg/ can help.
